### ISSUE TITLE
Test failures on Linux and MacOS

### ISSUE THREAD

**Issue by lesaltzm** [microsoft/PowerApps-Language-Tooling#128]

**Comment by MikeStall** [comment]
Issue #77 may also be related - newline encoding.

**Comment by SeaDude** [comment]
Test failure output. 
Ubuntu 20.10
```
user5@system5:~/Documents/powerapps/packUnpack/PowerApps-Language-Tooling$ ./build ci
ci: Starting... (ci)
ci: squeaky-clean: Starting...
Cleaning directory: /home/user5/Documents/powerapps/packUnpack/PowerApps-Language-Tooling/bin
Cleaning directory: /home/user5/Documents/powerapps/packUnpack/PowerApps-Language-Tooling/obj
Cleaning directory: /home/user5/Documents/powerapps/packUnpack/PowerApps-Language-Tooling/pkg
ci: squeaky-clean: Succeeded. (1.07 ms)
ci: clean: Starting...
targets: dotnet clean /home/user5/Documents/powerapps/packUnpack/PowerApps-Language-Tooling/src/PASopa.sln --configuration Debug /clp:verbosity=minimal /flp:Verbosity=normal;LogFile=/home/user5/Documents/powerapps/packUnpack/PowerApps-Language-Tooling/obj/logs/clean-Debug.log /flp3:PerformanceSummary;Verbosity=diag;LogFile=/home/user5/Documents/powerapps/packUnpack/PowerApps-Language-Tooling/obj/logs/clean-Debug.diagnostics.log -p:GitExists=true /nologo
ci: clean: Succeeded. (1.49 s)
ci: restore: Starting...
targets: dotnet restore /home/user5/Documents/powerapps/packUnpack/PowerApps-Language-Tooling/src/PASopa.sln /clp:verbosity=minimal /flp:Verbosity=normal;LogFile=/home/user5/Documents/powerapps/packUnpack/PowerApps-Language-Tooling/obj/logs/restore-Debug.log /flp3:PerformanceSummary;Verbosity=diag;LogFile=/home/user5/Documents/powerapps/packUnpack/PowerApps-Language-Tooling/obj/logs/restore-Debug.diagnostics.log -p:GitExists=true /nologo
  Determining projects to restore...
  Restored /home/user5/Documents/powerapps/packUnpack/PowerApps-Language-Tooling/src/PASopa/PASopa.csproj (in 1.23 sec).
  Restored /home/user5/Documents/powerapps/packUnpack/PowerApps-Language-Tooling/src/PAModel/Microsoft.PowerPlatform.Formulas.Tools.csproj (in 2.79 sec).
  Restored /home/user5/Documents/powerapps/packUnpack/PowerApps-Language-Tooling/src/PAModelTests/PAModelTests.csproj (in 17.42 sec).
ci: restore: Succeeded. (18.5 s)
ci: build: Starting...
targets: dotnet build /home/user5/Documents/powerapps/packUnpack/PowerApps-Language-Tooling/src/PASopa.sln --configuration Debug --no-restore /clp:verbosity=minimal /flp:Verbosity=normal;LogFile=/home/user5/Documents/powerapps/packUnpack/PowerApps-Language-Tooling/obj/logs/build-Debug.log /flp3:PerformanceSummary;Verbosity=diag;LogFile=/home/user5/Documents/powerapps/packUnpack/PowerApps-Language-Tooling/obj/logs/build-Debug.diagnostics.log -p:GitExists=true /nologo
  Microsoft.PowerPlatform.Formulas.Tools -> /home/user5/Documents/powerapps/packUnpack/PowerApps-Language-Tooling/bin/Debug/PAModel/Microsoft.PowerPlatform.Formulas.Tools.dll
  PAModelTests -> /home/user5/Documents/powerapps/packUnpack/PowerApps-Language-Tooling/bin/Debug/PAModelTests/PAModelTests.dll
  PASopa -> /home/user5/Documents/powerapps/packUnpack/PowerApps-Language-Tooling/bin/Debug/PASopa/PASopa.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:03.38
ci: build: Succeeded. (3.83 s)
ci: rebuild: Succeeded.
ci: test: Starting...
targets: dotnet test /home/user5/Documents/powerapps/packUnpack/PowerApps-Language-Tooling/src/PASopa.sln --configuration Debug --no-build --logger trx --results-directory /home/user5/Documents/powerapps/packUnpack/PowerApps-Language-Tooling/obj/testLogs /clp:verbosity=minimal /flp:Verbosity=normal;LogFile=/home/user5/Documents/powerapps/packUnpack/PowerApps-Language-Tooling/obj/logs/test-Debug.log /flp3:PerformanceSummary;Verbosity=diag;LogFile=/home/user5/Documents/powerapps/packUnpack/PowerApps-Language-Tooling/obj/logs/test-Debug.diagnostics.log -p:GitExists=true /nologo
Test run for /home/user5/Documents/powerapps/packUnpack/PowerApps-Language-Tooling/bin/Debug/PAModelTests/PAModelTests.dll (.NETCoreApp,Version=v3.1)
Microsoft (R) Test Execution Command Line Tool Version 16.8.3
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
  Failed TestChecksum [92 ms]
  Failed TestChecksum (MyWeather.msapp,C4_1GvK+QUkZ6kN+po5NnTEvX2IMFL5a56dTbSSN0icOYc=,11,References\DataSources.json,C4_dXkScH2mYpGGZ7ahgd864Zx5vsP51QYiH+eqPJV1KQ8=) [88 ms]
  Error Message:
   Assert.AreEqual failed. Expected:<C4_1GvK+QUkZ6kN+po5NnTEvX2IMFL5a56dTbSSN0icOYc=>. Actual:<C4_dF3ZiT6eOJeXvcVwSRn9PNVFRjYd0wz8Ojtqu0F9iWI=>. 
  Stack Trace:
     at PAModelTests.ChecksumTests.TestChecksum(String filename, String expectedChecksum, Int32 expectedFileCount, String file, String innerExpectedChecksum) in /home/user5/Documents/powerapps/packUnpack/PowerApps-Language-Tooling/src/PAModelTests/ChecksumTests.cs:line 23

  Failed TestMethod1 [18 s]
  Failed TestMethod1 (MyWeather.msapp) [348 ms]
  Error Message:
   Assert.IsTrue failed. 
  Stack Trace:
     at PAModelTests.RoundtripTests.TestMethod1(String filename) in /home/user5/Documents/powerapps/packUnpack/PowerApps-Language-Tooling/src/PAModelTests/RoundtripTests.cs:line 33

  Standard Output Messages:
 Microsoft.PowerPlatform.Formulas.Tools.DocumentException: Exception of type 'Microsoft.PowerPlatform.Formulas.Tools.DocumentException' was thrown.
    at Microsoft.PowerPlatform.Formulas.Tools.ErrorContainer.ThrowOnErrors() in /home/user5/Documents/powerapps/packUnpack/PowerApps-Language-Tooling/src/PAModel/PAConvert/ErrorContainer.cs:line 36
    at Microsoft.PowerPlatform.Formulas.Tools.MsAppTest.StressTest(String pathToMsApp) in /home/user5/Documents/powerapps/packUnpack/PowerApps-Language-Tooling/src/PAModel/MsAppTest.cs:line 58


  Failed TestMethod1 (Chess_for_Power_Apps_v1.03.msapp) [1 s]
  Error Message:
   Assert.IsTrue failed. 
  Stack Trace:
     at PAModelTests.RoundtripTests.TestMethod1(String filename) in /home/user5/Documents/powerapps/packUnpack/PowerApps-Language-Tooling/src/PAModelTests/RoundtripTests.cs:line 33

  Standard Output Messages:
 Microsoft.PowerPlatform.Formulas.Tools.DocumentException: Exception of type 'Microsoft.PowerPlatform.Formulas.Tools.DocumentException' was thrown.
    at Microsoft.PowerPlatform.Formulas.Tools.ErrorContainer.ThrowOnErrors() in /home/user5/Documents/powerapps/packUnpack/PowerApps-Language-Tooling/src/PAModel/PAConvert/ErrorContainer.cs:line 36
    at Microsoft.PowerPlatform.Formulas.Tools.MsAppTest.StressTest(String pathToMsApp) in /home/user5/Documents/powerapps/packUnpack/PowerApps-Language-Tooling/src/PAModel/MsAppTest.cs:line 58


  Failed TestMethod1 (AppWithLabel.msapp) [71 ms]
  Error Message:
   Assert.IsTrue failed. 
  Stack Trace:
     at PAModelTests.RoundtripTests.TestMethod1(String filename) in /home/user5/Documents/powerapps/packUnpack/PowerApps-Language-Tooling/src/PAModelTests/RoundtripTests.cs:line 33

  Standard Output Messages:
 Microsoft.PowerPlatform.Formulas.Tools.DocumentException: Exception of type 'Microsoft.PowerPlatform.Formulas.Tools.DocumentException' was thrown.
    at Microsoft.PowerPlatform.Formulas.Tools.ErrorContainer.ThrowOnErrors() in /home/user5/Documents/powerapps/packUnpack/PowerApps-Language-Tooling/src/PAModel/PAConvert/ErrorContainer.cs:line 36
    at Microsoft.PowerPlatform.Formulas.Tools.MsAppTest.StressTest(String pathToMsApp) in /home/user5/Documents/powerapps/packUnpack/PowerApps-Language-Tooling/src/PAModel/MsAppTest.cs:line 58


  Failed TestMethod1 (GalleryTestApp.msapp) [290 ms]
  Error Message:
   Assert.IsTrue failed. 
  Stack Trace:
     at PAModelTests.RoundtripTests.TestMethod1(String filename) in /home/user5/Documents/powerapps/packUnpack/PowerApps-Language-Tooling/src/PAModelTests/RoundtripTests.cs:line 33

  Standard Output Messages:
 Microsoft.PowerPlatform.Formulas.Tools.DocumentException: Exception of type 'Microsoft.PowerPlatform.Formulas.Tools.DocumentException' was thrown.
    at Microsoft.PowerPlatform.Formulas.Tools.ErrorContainer.ThrowOnErrors() in /home/user5/Documents/powerapps/packUnpack/PowerApps-Language-Tooling/src/PAModel/PAConvert/ErrorContainer.cs:line 36
    at Microsoft.PowerPlatform.Formulas.Tools.MsAppTest.StressTest(String pathToMsApp) in /home/user5/Documents/powerapps/packUnpack/PowerApps-Language-Tooling/src/PAModel/MsAppTest.cs:line 58


  Failed TestMethod1 (AccountPlanReviewerMaster.msapp) [15 s]
  Error Message:
   Assert.IsTrue failed. 
  Stack Trace:
     at PAModelTests.RoundtripTests.TestMethod1(String filename) in /home/user5/Documents/powerapps/packUnpack/PowerApps-Language-Tooling/src/PAModelTests/RoundtripTests.cs:line 33

  Standard Output Messages:
 Microsoft.PowerPlatform.Formulas.Tools.DocumentException: Exception of type 'Microsoft.PowerPlatform.Formulas.Tools.DocumentException' was thrown.
    at Microsoft.PowerPlatform.Formulas.Tools.ErrorContainer.ThrowOnErrors() in /home/user5/Documents/powerapps/packUnpack/PowerApps-Language-Tooling/src/PAModel/PAConvert/ErrorContainer.cs:line 36
    at Microsoft.PowerPlatform.Formulas.Tools.MsAppTest.StressTest(String pathToMsApp) in /home/user5/Documents/powerapps/packUnpack/PowerApps-Language-Tooling/src/PAModel/MsAppTest.cs:line 58


  Failed TestMethod1 (Marc2PowerPlatformDevOpsAlm.msapp) [1 s]
  Error Message:
   Assert.IsTrue failed. 
  Stack Trace:
     at PAModelTests.RoundtripTests.TestMethod1(String filename) in /home/user5/Documents/powerapps/packUnpack/PowerApps-Language-Tooling/src/PAModelTests/RoundtripTests.cs:line 33

  Standard Output Messages:
 Microsoft.PowerPlatform.Formulas.Tools.DocumentException: Exception of type 'Microsoft.PowerPlatform.Formulas.Tools.DocumentException' was thrown.
    at Microsoft.PowerPlatform.Formulas.Tools.ErrorContainer.ThrowOnErrors() in /home/user5/Documents/powerapps/packUnpack/PowerApps-Language-Tooling/src/PAModel/PAConvert/ErrorContainer.cs:line 36
    at Microsoft.PowerPlatform.Formulas.Tools.MsAppTest.StressTest(String pathToMsApp) in /home/user5/Documents/powerapps/packUnpack/PowerApps-Language-Tooling/src/PAModel/MsAppTest.cs:line 58


  Failed TestMethod1 (SimpleScopeVariables.msapp) [118 ms]
  Error Message:
   Assert.IsTrue failed. 
  Stack Trace:
     at PAModelTests.RoundtripTests.TestMethod1(String filename) in /home/user5/Documents/powerapps/packUnpack/PowerApps-Language-Tooling/src/PAModelTests/RoundtripTests.cs:line 33

  Standard Output Messages:
 Microsoft.PowerPlatform.Formulas.Tools.DocumentException: Exception of type 'Microsoft.PowerPlatform.Formulas.Tools.DocumentException' was thrown.
    at Microsoft.PowerPlatform.Formulas.Tools.ErrorContainer.ThrowOnErrors() in /home/user5/Documents/powerapps/packUnpack/PowerApps-Language-Tooling/src/PAModel/PAConvert/ErrorContainer.cs:line 36
    at Microsoft.PowerPlatform.Formulas.Tools.MsAppTest.StressTest(String pathToMsApp) in /home/user5/Documents/powerapps/packUnpack/PowerApps-Language-Tooling/src/PAModel/MsAppTest.cs:line 58


  Failed TestMethod1 (WadlConnector.msapp) [72 ms]
  Error Message:
   Assert.IsTrue failed. 
  Stack Trace:
     at PAModelTests.RoundtripTests.TestMethod1(String filename) in /home/user5/Documents/powerapps/packUnpack/PowerApps-Language-Tooling/src/PAModelTests/RoundtripTests.cs:line 33

  Standard Output Messages:
 Microsoft.PowerPlatform.Formulas.Tools.DocumentException: Exception of type 'Microsoft.PowerPlatform.Formulas.Tools.DocumentException' was thrown.
    at Microsoft.PowerPlatform.Formulas.Tools.ErrorContainer.ThrowOnErrors() in /home/user5/Documents/powerapps/packUnpack/PowerApps-Language-Tooling/src/PAModel/PAConvert/ErrorContainer.cs:line 36
    at Microsoft.PowerPlatform.Formulas.Tools.MsAppTest.StressTest(String pathToMsApp) in /home/user5/Documents/powerapps/packUnpack/PowerApps-Language-Tooling/src/PAModel/MsAppTest.cs:line 58


  Failed TestScreenBaselines [192 ms]
  Failed TestScreenBaselines (SimpleScopeVariables.msapp,Components\Component1.pa.yaml,ComponentFunction_Test.pa.yaml) [37 ms]
  Error Message:
   Test method PAModelTests.SourceDecoderTests.TestScreenBaselines threw exception: 
System.IO.FileNotFoundException: Could not find file '/tmp/35599c0c-ffcf-43fa-a0b2-bd09abc8afd2/Src/Components\Component1.pa.yaml'.
  Stack Trace:
      at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding)
   at System.IO.File.ReadAllText(String path)
   at PAModelTests.SourceDecoderTests.AssertFilesEqual(String pathExpected, String pathActual) in /home/user5/Documents/powerapps/packUnpack/PowerApps-Language-Tooling/src/PAModelTests/SourceDecoderTests.cs:line 50
   at PAModelTests.SourceDecoderTests.TestScreenBaselines(String appName, String sourceFileName, String screenBaselineName) in /home/user5/Documents/powerapps/packUnpack/PowerApps-Language-Tooling/src/PAModelTests/SourceDecoderTests.cs:line 43

  Failed TestScreenBaselines (TestStudio_Test.msapp,Tests\Test_7F478737223C4B69.pa.yaml,TestStudio_Test.pa.yaml) [33 ms]
  Error Message:
   Test method PAModelTests.SourceDecoderTests.TestScreenBaselines threw exception: 
System.IO.FileNotFoundException: Could not find file '/tmp/a42d6957-9e55-412e-8cde-efaf8b7483d5/Src/Tests\Test_7F478737223C4B69.pa.yaml'.
  Stack Trace:
      at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding)
   at System.IO.File.ReadAllText(String path)
   at PAModelTests.SourceDecoderTests.AssertFilesEqual(String pathExpected, String pathActual) in /home/user5/Documents/powerapps/packUnpack/PowerApps-Language-Tooling/src/PAModelTests/SourceDecoderTests.cs:line 50
   at PAModelTests.SourceDecoderTests.TestScreenBaselines(String appName, String sourceFileName, String screenBaselineName) in /home/user5/Documents/powerapps/packUnpack/PowerApps-Language-Tooling/src/PAModelTests/SourceDecoderTests.cs:line 43

Results File: /home/user5/Documents/powerapps/packUnpack/PowerApps-Language-Tooling/obj/testLogs/_system5_2021-01-26_18_57_24.trx

Failed!  - Failed:    11, Passed:    64, Skipped:     0, Total:    75, Duration: 19 s - /home/user5/Documents/powerapps/packUnpack/PowerApps-Language-Tooling/bin/Debug/PAModelTests/PAModelTests.dll (netcoreapp3.1)
ci: test: Failed! The command exited with code 1. (21.7 s)
ci: ────────────────────────────────────────
ci: Target         Outcome    Duration      
ci: ─────────────  ─────────  ──────────────
ci: squeaky-clean  Succeeded  1 ms     0.0% 
ci: clean          Succeeded  1.49 s   3.3% 
ci: restore        Succeeded  18.49 s  40.6%
ci: build          Succeeded  3.83 s   8.4% 
ci: rebuild        Succeeded                
ci: test           Failed!    21.72 s  47.7%
ci: ────────────────────────────────────────
ci: Failed! (ci) (45.5 s)

```

**Comment by SeaDude** [comment]
Looks like an escape issue or Windows "\" vs. nonWindows "/" issue(?)
`/tmp/a42d6957-9e55-412e-8cde-efaf8b7483d5/Src/Tests**\**Test_7F478737223C4B69.pa.yaml`
