### ISSUE TITLE
Error when unpacking on `.msapp`

### ISSUE THREAD

**Issue by nmedda** [microsoft/PowerApps-Language-Tooling#310]
I just installed the latest version and I got an error when unpacking:

```
PS C:\Users\NicolasMedda\Documents\Projets\mh360\MH360Partenaires\CanvasApps> pac canvas unpack --msapp .\new_applicationauditetcontrlepermanent_7caa7_DocumentUri.msapp
UnPack from C:\Users\NicolasMedda\Documents\Projets\mh360\MH360Partenaires\CanvasApps\new_applicationauditetcontrlepermanent_7caa7_DocumentUri.msapp-->C:\Users\NicolasMedda\Documents\Projets\mh360\MH360Partenaires\CanvasApps
Désolé, l'application a rencontré une erreur non récupérable et doit être fermée. Les détails de l'exception ont été capturés et seront transmis à l'équipe de développement, si la télémétrie a été activée. ID de l'exception :cbcc9b32-5b11-4aff-910f-9f4128aff50c
PS C:\Users\NicolasMedda\Documents\Projets\mh360\MH360Partenaires\CanvasApps>
```

Is there a way to know what the exception is?
Maybe through a verbose parameter or something, but it would really help understand what's going on.

Thanks

**Comment by nmedda** [comment]
After changing the version (thanks for `pac use` BTW), I figured it needed the `--sources` parameter set.

The command ` pac canvas unpack --msapp .\new_applicationauditetcontrlepermanent_7caa7_DocumentUri.msapp --sources auditetcontrolpermanent`
works with 1.9.4 but doesn't with 1.9.8+g642d61a

Here's the exception id with the correct command: `f4a525a7-7c79-4236-bd06-ebfe91d88f65`

**Comment by jenschristianschroder** [comment]
I experience the same behavior with 1.9.8

Cannot unpack canvas app

Error message:
Sorry, the app encountered a non recoverable error and will need to terminate. The exception details have been captured and will be forwarded to the development team, if telemetry has been enabled. Exception Id:91cb509d-35d2-42e2-ad7a-e77d765dad80

works with 1.9.4 but not 1.9.8

**Comment by mikefactorial** [comment]
Related issue workaround for ALM Accelerators /microsoft/coe-starter-kit/#1272

**Comment by coatsy** [comment]
+ 1 for a more descriptive error message

**Comment by FlexiGit** [comment]
I get this error, too, after updating the AA4AM build templates. 
The PowerApps solution I try to export/import has ManifestVersion 0.20. I understand the minimal supported version for the pac cli is 0.24. Is there anything I can do to upgrade the solution to newer ManifestVersion?

**Comment by FlexiGit** [comment]
> @FlexiGit,
> 
> Until the fix is publish for PAC CLI there is a workaround described here [microsoft/coe-starter-kit#1272](https://github.com/microsoft/coe-starter-kit/issues/1272)

I have seen that. Unfortunately that does not help in my case. Version 1.9.4 of pac cli has the minimal version requirement of ManifestVersion 0.24, too.
Previously I was using the temporary unpack solution published with the build templates (not the pac cli).

**Comment by MarrinerDev** [comment]
Not sure where to report this. PowerPlatform CLI, Version: 1.9.9+g8a4823f.

pac canvas unpack --msapp SomeApp.msapp --sources SrcFld

 I just exported the MSAPP file for my canvas PowerApp and I'm getting the extremely helpful error: "Sorry, the app encountered a non recoverable error and will need to terminate."
When I run the same command across a version of the app I exported in August, it works.
So despite several posts I've seen here, the problem is not fixed.

**Comment by JackBruceDev** [comment]
I had the same issue with @MarrinerDev, the problem happens for newly exported .msapp file.

**Comment by kiranreloaded** [comment]
Same Issue. This is not working.
Microsoft PowerPlatform CLI
Version: 1.9.9+g8a4823f

Sorry, the app encountered a non recoverable error and will need to terminate. The exception details have been captured and will be forwarded to the development team, if telemetry has been enabled. Exception Id:6193e2bb-8168-4515-b149-0d5eb20e5389

**Comment by rcopelandburgundy** [comment]
I can also replicate this issue with Version: 1.9.9+g8a4823f. It happens for a specific app, but other apps unpack successfully.

**Comment by jjkinsey** [comment]
I am also experiencing this issue (versions `1.9.9+g8a4823f` and `1.9.8+g642d61a`) with newly exported `.msapp` files.

**Comment by megel** [comment]
Any updates, I have the same problem with versions 1.9.9+g8a4823f 😥. Furthermore I can't switch to older versions.

**Comment by JackBruceDev** [comment]
I think there is similar issue that reported here:
[https://github.com/microsoft/PowerApps-Language-Tooling/issues/319](url)
Seem like it was fixed and will be released in next version.

**Comment by samuel-weber** [comment]
Me too: Still facing this issue with version 1.9.9

**Comment by seancale** [comment]
Still experiencing this issue on version 1.10.4+gf23be2f

**Comment by jjkinsey** [comment]
@seancale With a newly exported `.msapp` file? I'm able to unpack Canvas apps using `pac` version `1.10.4+gf23be2f`. (My Power Apps release is `3.21114.18`; I assume that's relevant.)

**Comment by seancale** [comment]
@jjkinsey Yes, my app was just exported a couple of hours ago. I'm experiencing the lack of helpful error messages. I can unpack apps just fine but I get a nondescript error message when trying to pack them.

**Comment by jjkinsey** [comment]
@seancale What's the error? I'm able to round-trip apps, though I do get a warning message on unpack:
```
$ pac canvas unpack --msapp test.msapp --sources test
UnPack from /home/kinsey/test.msapp-->/home/kinsey/test
Warning PA2001: Checksum mismatch. Checksum doesn't match on extract.
Warning PA2001: Checksum mismatch. File References\DataSources.json checksum does not match on extract
  source format version: 0.24
$ pac canvas pack --sources test--msapp repack.msapp
Pack from /home/kinsey/test-->/home/test/repack.msapp
  source format version: 0.24
```

**Comment by seancale** [comment]
@jjkinsey 
Here's what I'm getting from the output:

```
PS C:\[redacted]\CanvasApps> pac canvas pack --sources .\[redacted-app] --msapp [redacted].msapp
Pack from C:\[redacted]\CanvasApps\[redacted-app]i-->C:\[redacted]\CanvasApps\[redacted].msapp
  source format version: 0.24
Sorry, the app encountered a non recoverable error and will need to terminate. The exception details have been captured and will be forwarded to the development team, if telemetry has been enabled. Exception Id:23c85b28-c19a-41b4-8aa2-13f0876c27a1
```

There's no warnings or errors being printed. Out of curiosity, I cloned this repository, and ran the pack command inside a Visual Studio debug session and got this exception instead:

```
System.Text.Json.JsonReaderException
  HResult=0x80131500
  Message='0xEF' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.
  Source=System.Text.Json
  StackTrace:
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadFirstToken(Byte first)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.JsonDocument.Parse(ReadOnlySpan`1 utf8JsonSpan, Utf8JsonReader reader, MetadataDb& database, StackRowStack& stack)
   at System.Text.Json.JsonDocument.Parse(ReadOnlyMemory`1 utf8Json, JsonReaderOptions readerOptions, Byte[] extraRentedBytes)
   at System.Text.Json.JsonDocument.Parse(ReadOnlyMemory`1 utf8Json, JsonDocumentOptions options)
   at Microsoft.PowerPlatform.Formulas.Tools.ChecksumMaker.ChecksumJsonFile[T](String filename, Byte[] bytes) in C:\[redacted]\PowerApps-Language-Tooling\src\PAModel\Checksum\ChecksumMaker.cs:line 170
   at Microsoft.PowerPlatform.Formulas.Tools.ChecksumMaker.ChecksumFile[T](String filename, Byte[] bytes) in C:\[redacted]\PowerApps-Language-Tooling\src\PAModel\Checksum\ChecksumMaker.cs:line 76
   at Microsoft.PowerPlatform.Formulas.Tools.ChecksumMaker.AddFile(String filename, Byte[] bytes) in C:\[redacted]\PowerApps-Language-Tooling\src\PAModel\Checksum\ChecksumMaker.cs:line 55
   at Microsoft.PowerPlatform.Formulas.Tools.MsAppSerializer.SaveAsMsApp(CanvasDocument app, String fullpathToMsApp, ErrorContainer errors, Boolean isValidation) in C:\[redacted]\PowerApps-Language-Tooling\src\PAModel\Serializers\MsAppSerializer.cs:line 411
   at Microsoft.PowerPlatform.Formulas.Tools.CanvasDocument.<>c__DisplayClass31_0.<SaveToMsApp>b__0() in C:\[redacted]\PowerApps-Language-Tooling\src\PAModel\CanvasDocument.cs:line 153
   at Microsoft.PowerPlatform.Formulas.Tools.CanvasDocument.Wrapper(Action worker, ErrorContainer errors) in C:\[redacted]\PowerApps-Language-Tooling\src\PAModel\CanvasDocument.cs:line 249
   at Microsoft.PowerPlatform.Formulas.Tools.CanvasDocument.SaveToMsApp(String fullPathToMsApp) in C:\[redacted]\PowerApps-Language-Tooling\src\PAModel\CanvasDocument.cs:line 153
   at PASopa.Program.<>c__DisplayClass0_1.<Main>b__2() in C:\[redacted]\PowerApps-Language-Tooling\src\PASopa\Program.cs:line 123
   at PASopa.Program.TryOperation(Func`1 operation) in C:\[redacted]\PowerApps-Language-Tooling\src\PASopa\Program.cs:line 247

  This exception was originally thrown at this call stack:
    [External Code]
    Microsoft.PowerPlatform.Formulas.Tools.ChecksumMaker.ChecksumJsonFile<T>(string, byte[]) in ChecksumMaker.cs
    Microsoft.PowerPlatform.Formulas.Tools.ChecksumMaker.ChecksumFile<T>(string, byte[]) in ChecksumMaker.cs
    Microsoft.PowerPlatform.Formulas.Tools.ChecksumMaker.AddFile(string, byte[]) in ChecksumMaker.cs
    Microsoft.PowerPlatform.Formulas.Tools.MsAppSerializer.SaveAsMsApp(Microsoft.PowerPlatform.Formulas.Tools.CanvasDocument, string, Microsoft.PowerPlatform.Formulas.Tools.ErrorContainer, bool) in MsAppSerializer.cs
    Microsoft.PowerPlatform.Formulas.Tools.CanvasDocument.SaveToMsApp.AnonymousMethod__0() in CanvasDocument.cs
    Microsoft.PowerPlatform.Formulas.Tools.CanvasDocument.Wrapper(System.Action, Microsoft.PowerPlatform.Formulas.Tools.ErrorContainer) in CanvasDocument.cs
    Microsoft.PowerPlatform.Formulas.Tools.CanvasDocument.SaveToMsApp(string) in CanvasDocument.cs
    PASopa.Program.Main.AnonymousMethod__2() in Program.cs
    PASopa.Program.TryOperation(System.Func<Microsoft.PowerPlatform.Formulas.Tools.ErrorContainer>) in Program.cs
```

It seems to be a file encoding issue coming from the JSON parser. All of my JSON files are encoded as UTF-8 but I think something in my environment might be adding a BOM without my knowledge. I forgot to mention that these are modified files from my custom source control solution, so I'm confident that's what's causing my problems.

**Comment by jjkinsey** [comment]
Ah, okay. It might be worth posting in another issue (maybe https://github.com/microsoft/PowerApps-Language-Tooling/issues/311?) about this; this issue was more about a specific (now resolved) problem with unpacking apps.
