### ISSUE TITLE
Unpack fails with error

### ISSUE THREAD

**Issue by DaveStabilify** [microsoft/PowerApps-Language-Tooling#385]
- [ ] Please attach a sample .msapp to this Issue which demonstrates the issue you are experiencing. *(Please do not attach any file which may contain sensitive personal or company data.)*
- [ ] Cannot attach file because of sensitive data.

**Describe the bug**

Error   PA3001: Internal error. An item with the same key has already been added. Key: Microsoft.PowerPlatform.Formulas.Tools.Utility.FilePath
Stack Trace:
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Microsoft.PowerPlatform.Formulas.Tools.CanvasDocument.StabilizeAssetFilePaths(ErrorContainer errors) in C:\Users\Dave\Documents\GitHub\PowerApps-Language-Tooling\src\PAModel\CanvasDocument.cs:line 587
   at Microsoft.PowerPlatform.Formulas.Tools.CanvasDocument.ApplyAfterMsAppLoadTransforms(ErrorContainer errors) in C:\Users\Dave\Documents\GitHub\PowerApps-Language-Tooling\src\PAModel\CanvasDocument.cs:line 394
   at Microsoft.PowerPlatform.Formulas.Tools.MsAppSerializer.Load(Stream streamToMsapp, ErrorContainer errors) in C:\Users\Dave\Documents\GitHub\PowerApps-Language-Tooling\src\PAModel\Serializers\MsAppSerializer.cs:line 417
   at Microsoft.PowerPlatform.Formulas.Tools.CanvasDocument.<>c__DisplayClass29_1.<LoadFromMsapp>b__0() in C:\Users\Dave\Documents\GitHub\PowerApps-Language-Tooling\src\PAModel\CanvasDocument.cs:line 128
   at Microsoft.PowerPlatform.Formulas.Tools.CanvasDocument.Wrapper(Func`1 worker, ErrorContainer errors) in C:\Users\Dave\Documents\GitHub\PowerApps-Language-Tooling\src\PAModel\CanvasDocument.cs:line 227
   at Microsoft.PowerPlatform.Formulas.Tools.CanvasDocument.LoadFromMsapp(String fullPathToMsApp) in C:\Users\Dave\Documents\GitHub\PowerApps-Language-Tooling\src\PAModel\CanvasDocument.cs:line 128
   at PASopa.Program.<>c__DisplayClass0_0.<Main>b__1() in C:\Users\Dave\Documents\GitHub\PowerApps-Language-Tooling\src\PASopa\Program.cs:line 135
   at PASopa.Program.TryOperation(Func`1 operation) in C:\Users\Dave\Documents\GitHub\PowerApps-Language-Tooling\src\PASopa\Program.cs:line 280

**To Reproduce**

1. Unpacking or packing 

**Screenshots**

If applicable, add screenshots of error messages to help explain your problem.

**Additional context**

Add any helpful context on the .msapp like created from teams, contains custom pcf components, etc.

**Comment by NavneetThekkumpat** [comment]
@DaveStabilify : Can you confirm if this was reproduced using PAC Cli or PASopa? Also please specify the version used. Thank you

**Comment by davidjenni** [comment]
@DaveStabilify this seems to be the same issue as what you logged in microsoft/powerplatform-vscode#188, but one repro with PASopa (this 385) and the other in pac CLI (188)?
As requested in 188, our internal team will likely need the .msapp for a repro

CC @NavneetThekkumpat

**Comment by NavneetThekkumpat** [comment]
@DaveStabilify : From error logs above, it looks like 

- It seems like an asset name collision. 
- That said, please confirm if there are multiple assets with the same name. If so, try changing the name to be different.
- If its an image asset, try changing 
![image](https://user-images.githubusercontent.com/98551644/164251415-76592fd2-0040-4e32-8595-c01c5f1aa3c6.png)
- To confirm the renaming, you could unzip the .msapp. Then asset details (including Name) could be found in References/Resources.json and assets are found in the Assets folder.

You could try this as a workaround.

**Comment by NavneetThekkumpat** [comment]
@DaveStabilify Also can you confirm the version of PAC or PASopa used ?

**Comment by landonarogers** [comment]
This fix will be available in the next version of PAC CLI.
